theme: jekyll-theme-cayman
title: The Proteus Institute
description: Creating bio-inspired and biological machines.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
